import Link from "next/link";
import QRCode from "qrcode";
import { ExternalLink, Palette, Clock3, MapPin, QrCode, Plus, Trash2 } from "lucide-react";
import { getCurrentCompany } from "@/lib/auth/current-company";
import { addDeliveryZone, deleteDeliveryZone, saveBusinessHours, saveMenuSettings, toggleDeliveryZone } from "./actions";
import { CopyLinkButton } from "./copy-link-button";

const days = ["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"];
const money = (v: number | string | null | undefined) => Number(v || 0).toFixed(2).replace(".", ",");

export default async function Page({ searchParams }: { searchParams: Promise<{ erro?: string; sucesso?: string }> }) {
  const query = await searchParams;
  const { supabase, company } = await getCurrentCompany();
  const [{ data: settings }, { data: hours }, { data: zones }] = await Promise.all([
    supabase.from("companies").select("name,slug,logo_url,banner_url,primary_color,accent_color,secondary_color,menu_layout,menu_message,menu_is_active,delivery_minimum,default_delivery_fee,pickup_enabled,delivery_enabled,average_delivery_minutes,whatsapp,address_line,city,state,postal_code").eq("id", company.id).single(),
    supabase.from("business_hours").select("weekday,is_open,opens_at,closes_at").eq("company_id", company.id).order("weekday"),
    supabase.from("delivery_zones").select("id,name,delivery_fee,minimum_order,estimated_minutes,is_active").eq("company_id", company.id).order("name"),
  ]);
  const origin = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
  const menuUrl = `${origin}/cardapio/${settings?.slug || company.slug}`;
  const qr = await QRCode.toDataURL(menuUrl, { width: 320, margin: 1 });
  const hourMap = new Map((hours || []).map(h => [h.weekday, h]));

  return <main className="space-y-8 pb-16">
    <header><p className="text-sm font-semibold text-emerald-700">Identidade e operação</p><h1 className="text-3xl font-bold">Configuração do cardápio</h1><p className="mt-2 text-gray-600">Personalize a loja, os horários, as taxas e gere seu QR Code.</p></header>
    {query.erro && <div className="rounded-xl bg-red-50 p-4 text-red-700">{query.erro}</div>}
    {query.sucesso && <div className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{query.sucesso}</div>}

    <section className="grid gap-6 xl:grid-cols-[1fr_360px]">
      <form action={saveMenuSettings} className="space-y-6 rounded-2xl border bg-white p-6 shadow-sm">
        <div className="flex items-center gap-3"><Palette className="text-emerald-700"/><div><h2 className="text-xl font-bold">Aparência e dados da loja</h2><p className="text-sm text-gray-500">As alterações aparecem no cardápio público.</p></div></div>
        <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Nome da loja<input name="name" required defaultValue={settings?.name || company.name} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-semibold">Endereço do cardápio<input name="slug" required defaultValue={settings?.slug || company.slug} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label></div>
        <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">URL da logomarca<input name="logoUrl" defaultValue={settings?.logo_url || ""} placeholder="https://..." className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-semibold">URL do banner<input name="bannerUrl" defaultValue={settings?.banner_url || ""} placeholder="https://..." className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label></div>
        <div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-semibold">Cor principal<input type="color" name="primaryColor" defaultValue={settings?.primary_color || "#15803D"} className="mt-1 h-12 w-full rounded-xl border p-1"/></label><label className="text-sm font-semibold">Cor de destaque<input type="color" name="accentColor" defaultValue={settings?.accent_color || "#F97316"} className="mt-1 h-12 w-full rounded-xl border p-1"/></label><label className="text-sm font-semibold">Cor secundária<input type="color" name="secondaryColor" defaultValue={settings?.secondary_color || "#F97316"} className="mt-1 h-12 w-full rounded-xl border p-1"/></label></div>
        <label className="block text-sm font-semibold">Mensagem do cardápio<textarea name="menuMessage" defaultValue={settings?.menu_message || ""} rows={3} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal" placeholder="Ex.: Peça agora e receba quentinho!"/></label>
        <div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">WhatsApp<input name="whatsapp" defaultValue={settings?.whatsapp || ""} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-semibold">Layout<select name="menuLayout" defaultValue={settings?.menu_layout || "cards"} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"><option value="cards">Cards com fotos</option><option value="compact">Lista compacta</option></select></label><label className="text-sm font-semibold">Previsão média (min)<input type="number" min="5" name="averageDeliveryMinutes" defaultValue={settings?.average_delivery_minutes || 45} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label></div>
        <div className="grid gap-4 md:grid-cols-4"><label className="text-sm font-semibold md:col-span-2">Endereço<input name="addressLine" defaultValue={settings?.address_line || ""} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-semibold">Cidade<input name="city" defaultValue={settings?.city || ""} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-semibold">UF<input name="state" maxLength={2} defaultValue={settings?.state || ""} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label></div>
        <div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">CEP<input name="postalCode" defaultValue={settings?.postal_code || ""} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-semibold">Pedido mínimo (R$)<input name="deliveryMinimum" inputMode="decimal" defaultValue={money(settings?.delivery_minimum)} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label><label className="text-sm font-semibold">Taxa padrão (R$)<input name="defaultDeliveryFee" inputMode="decimal" defaultValue={money(settings?.default_delivery_fee)} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label></div>
        <div className="flex flex-wrap gap-5 rounded-xl bg-gray-50 p-4"><label className="flex items-center gap-2"><input type="checkbox" name="menuIsActive" defaultChecked={settings?.menu_is_active ?? true}/> Cardápio ativo</label><label className="flex items-center gap-2"><input type="checkbox" name="deliveryEnabled" defaultChecked={settings?.delivery_enabled ?? true}/> Delivery</label><label className="flex items-center gap-2"><input type="checkbox" name="pickupEnabled" defaultChecked={settings?.pickup_enabled ?? true}/> Retirada</label></div>
        <button className="w-full rounded-xl bg-emerald-700 px-5 py-3 font-semibold text-white">Salvar configurações</button>
      </form>

      <aside className="h-fit rounded-2xl border bg-white p-6 text-center shadow-sm xl:sticky xl:top-6"><QrCode className="mx-auto text-emerald-700"/><h2 className="mt-2 text-xl font-bold">QR Code da loja</h2><p className="mt-1 text-sm text-gray-500">Imprima e coloque no balcão, nas mesas ou embalagens.</p><img src={qr} alt="QR Code do cardápio" className="mx-auto mt-4 w-64 rounded-xl border"/><p className="mt-3 break-all rounded-xl bg-gray-50 p-3 text-xs">{menuUrl}</p><div className="mt-4 flex flex-wrap justify-center gap-2"><CopyLinkButton value={menuUrl}/><Link href={menuUrl} target="_blank" className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2 font-semibold text-white"><ExternalLink size={18}/> Abrir</Link></div><p className="mt-4 text-xs text-gray-500">Para usar o endereço publicado, configure <code>NEXT_PUBLIC_APP_URL</code>.</p></aside>
    </section>

    <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Clock3 className="text-emerald-700"/><div><h2 className="text-xl font-bold">Horários de funcionamento</h2><p className="text-sm text-gray-500">Defina quando o cardápio aceita pedidos.</p></div></div><form action={saveBusinessHours} className="mt-5 space-y-3">{days.map((day, index)=>{const h=hourMap.get(index);return <div key={day} className="grid items-center gap-3 rounded-xl bg-gray-50 p-3 sm:grid-cols-[160px_100px_1fr_1fr]"><strong>{day}</strong><label className="flex items-center gap-2 text-sm"><input type="checkbox" name={`open_${index}`} defaultChecked={h?.is_open ?? index !== 0}/> Aberto</label><input type="time" name={`opens_${index}`} defaultValue={String(h?.opens_at || "09:00").slice(0,5)} className="rounded-lg border px-3 py-2"/><input type="time" name={`closes_${index}`} defaultValue={String(h?.closes_at || "18:00").slice(0,5)} className="rounded-lg border px-3 py-2"/></div>})}<button className="rounded-xl bg-emerald-700 px-5 py-3 font-semibold text-white">Salvar horários</button></form></section>

    <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><MapPin className="text-emerald-700"/><div><h2 className="text-xl font-bold">Bairros e regiões atendidas</h2><p className="text-sm text-gray-500">Cada região pode ter taxa, pedido mínimo e prazo próprios.</p></div></div><form action={addDeliveryZone} className="mt-5 grid gap-3 md:grid-cols-5"><input name="name" required placeholder="Bairro ou região" className="rounded-xl border px-3 py-3 md:col-span-2"/><input name="deliveryFee" placeholder="Taxa R$" inputMode="decimal" className="rounded-xl border px-3 py-3"/><input name="minimumOrder" placeholder="Mínimo R$" inputMode="decimal" className="rounded-xl border px-3 py-3"/><div className="flex gap-2"><input name="estimatedMinutes" type="number" min="5" defaultValue="45" className="min-w-0 flex-1 rounded-xl border px-3 py-3"/><button title="Adicionar" className="rounded-xl bg-orange-500 px-4 text-white"><Plus/></button></div></form><div className="mt-5 divide-y rounded-xl border">{(zones||[]).length===0?<p className="p-5 text-gray-500">Nenhuma região cadastrada. A taxa padrão será usada.</p>:(zones||[]).map(z=><div key={z.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>{z.name}</strong><p className="text-sm text-gray-500">Taxa R$ {money(z.delivery_fee)} • mínimo R$ {money(z.minimum_order)} • {z.estimated_minutes} min</p></div><div className="flex gap-2"><form action={toggleDeliveryZone}><input type="hidden" name="id" value={z.id}/><input type="hidden" name="active" value={String(z.is_active)}/><button className={`rounded-lg px-3 py-2 text-sm font-semibold ${z.is_active?"bg-emerald-50 text-emerald-700":"bg-gray-100 text-gray-500"}`}>{z.is_active?"Ativa":"Inativa"}</button></form><form action={deleteDeliveryZone}><input type="hidden" name="id" value={z.id}/><button title="Excluir" className="rounded-lg bg-red-50 p-2 text-red-600"><Trash2 size={18}/></button></form></div></div>)}</div></section>

    <section className="rounded-2xl border border-orange-100 bg-orange-50 p-5"><h2 className="font-bold text-orange-900">Adicionais e complementos</h2><p className="mt-1 text-sm text-orange-800">Os grupos de adicionais continuam vinculados a cada produto. Abra Produtos para configurar tamanho, sabores, bordas, molhos e extras.</p><Link href="/produtos" className="mt-3 inline-flex font-semibold text-orange-800">Abrir produtos →</Link></section>
  </main>;
}
