"use client";
import { useParams } from "next/navigation";
import { Bike, CheckCircle2, Clock3 } from "lucide-react";
import { useDemoState } from "@/lib/demo/use-demo-state";
import { OrderStage, stageLabel } from "@/lib/demo/store";

const sequence:OrderStage[]=["novo","preparando","pronto","aguardando_motoboy","em_entrega","entregue"];
export default function TrackingPage(){
 const params=useParams<{code:string}>(); const {state,update}=useDemoState(); const id=(params.code||"").replace(/\D/g,"")||"452"; const order=state.orders.find(o=>o.id===id)||state.orders[0]; const index=sequence.indexOf(order.stage);
 const finish=()=>update(s=>({...s,orders:s.orders.map(o=>o.id===order.id?{...o,stage:"entregue",updatedAt:new Date().toISOString()}:o),drivers:s.drivers.map(d=>d.id===order.driverId?{...d,status:"available"}:d)}));
 return <main className="min-h-screen bg-[#f7faf8] p-4 md:p-8"><div className="mx-auto max-w-4xl"><header className="mb-6 flex items-center gap-3"><div className="rounded-xl bg-emerald-700 p-3 text-white"><Bike/></div><div><p className="font-bold text-emerald-800">MercadoFood</p><h1 className="text-2xl font-bold">Acompanhamento do pedido #{order.id}</h1></div></header><section className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-sm text-gray-500">Status atual</p><h2 className="text-2xl font-bold text-emerald-800">{stageLabel[order.stage]}</h2><div className="mt-6 space-y-0">{sequence.map((s,i)=>{const done=i<=index;return <div key={s} className="flex gap-3"><div className="flex flex-col items-center"><div className={`flex h-7 w-7 items-center justify-center rounded-full ${done?"bg-emerald-600 text-white":"bg-gray-100 text-gray-400"}`}>{done?<CheckCircle2 size={17}/>:<Clock3 size={15}/>}</div>{i<sequence.length-1&&<div className={`h-12 w-0.5 ${i<index?"bg-emerald-500":"bg-gray-200"}`}/>}</div><p className={`pt-1 ${done?"font-semibold text-emerald-800":"text-gray-500"}`}>{stageLabel[s]}</p></div>})}</div></article><article className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-sm text-gray-500">Entrega para</p><h2 className="text-xl font-bold">{order.customer}</h2><p className="mt-1 text-gray-600">{order.address}</p><div className="mt-6 rounded-2xl bg-emerald-50 p-5"><p className="font-semibold text-emerald-800">Rastreamento demonstrativo</p><p className="mt-1 text-sm text-emerald-700">Quando o GPS real for conectado, esta área mostrará a posição do motoboy no mapa.</p></div>{order.stage==="em_entrega"&&<button onClick={finish} className="mt-6 w-full rounded-xl bg-emerald-700 py-3 font-bold text-white">Simular entrega concluída</button>}{order.stage==="entregue"&&<div className="mt-6 rounded-xl bg-emerald-600 p-4 text-center font-bold text-white">Pedido entregue com sucesso!</div>}</article></section></div></main>
}
