"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requirePlatformStaff } from "@/lib/master/auth";
import { moduleLabels } from "@/lib/billing/plans";

const planSchema=z.object({id:z.string().uuid(),name:z.string().trim().min(2).max(80),description:z.string().max(500),monthlyPrice:z.union([z.literal(""),z.coerce.number().min(0)]),annualPrice:z.union([z.literal(""),z.coerce.number().min(0)]),annualDiscount:z.union([z.literal(""),z.coerce.number().min(0).max(100)]),status:z.enum(["active","inactive"]),visibility:z.enum(["public","hidden","internal"]),trialDays:z.coerce.number().int().min(0).max(365),productLimit:z.union([z.literal(""),z.coerce.number().int().min(0)]),orderLimit:z.union([z.literal(""),z.coerce.number().int().min(0)]),displayOrder:z.coerce.number().int().min(0),highlightLabel:z.enum(["","Mais escolhido","Mais popular"]),annualAdjustmentEnabled:z.enum(["true","false"]),annualAdjustmentMonth:z.union([z.literal(""),z.coerce.number().int().min(1).max(12)]),annualAdjustmentPercent:z.union([z.literal(""),z.coerce.number().min(0).max(100)]),annualAdjustmentMode:z.enum(["manual","automatic"]),annualNoticeDays:z.coerce.number().int().min(0).max(365),annualAdjustmentPolicy:z.string().max(2000)});
export async function updatePlan(formData:FormData){const {admin}=await requirePlatformStaff("master");const parsed=planSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)redirect("/master/planos?erro=Dados inválidos");const v=parsed.data;const annualPrice=v.annualPrice===""?null:v.annualPrice;const {error}=await admin.from("subscription_plans").update({name:v.name,description:v.description||null,monthly_price:v.monthlyPrice===""?null:v.monthlyPrice,annual_price:annualPrice,annual_monthly_price:annualPrice===null?null:Number((annualPrice/12).toFixed(2)),annual_discount_percent:v.annualDiscount===""?null:v.annualDiscount,is_active:v.status==="active",visibility:v.visibility,trial_days:v.trialDays,product_limit:v.productLimit===""?null:v.productLimit,order_limit:v.orderLimit===""?null:v.orderLimit,display_order:v.displayOrder,highlight_label:v.highlightLabel||null,annual_adjustment_enabled:v.annualAdjustmentEnabled==="true",annual_adjustment_month:v.annualAdjustmentMonth===""?null:v.annualAdjustmentMonth,annual_adjustment_percent:v.annualAdjustmentPercent===""?null:v.annualAdjustmentPercent,annual_adjustment_mode:v.annualAdjustmentMode,annual_notice_days:v.annualNoticeDays,annual_adjustment_policy:v.annualAdjustmentPolicy||null,updated_at:new Date().toISOString()}).eq("id",v.id);if(error)redirect(`/master/planos?erro=${encodeURIComponent(error.message)}`);revalidatePath("/master/planos");revalidatePath("/master/empresas")}
export async function updatePlanFeatures(formData:FormData){const {admin}=await requirePlatformStaff("master");const planId=String(formData.get("planId")||"");if(!z.string().uuid().safeParse(planId).success)redirect("/master/planos?erro=Plano inválido");const selected=formData.getAll("features").map(String);const rows=Object.keys(moduleLabels).map(moduleKey=>({plan_id:planId,module_key:moduleKey,enabled:selected.includes(moduleKey),updated_at:new Date().toISOString()}));const {error}=await admin.from("plan_entitlements").upsert(rows,{onConflict:"plan_id,module_key"});if(error)redirect(`/master/planos?erro=${encodeURIComponent(error.message)}`);revalidatePath("/master/planos")}
export async function schedulePriceAdjustment(formData:FormData){const {admin,user}=await requirePlatformStaff("master");const planId=String(formData.get("planId")||"");const type=String(formData.get("adjustmentType")||"");const amount=Number(formData.get("amount"));const effectiveAt=String(formData.get("effectiveAt")||"");const reason=String(formData.get("reason")||"").trim();const selected=formData.getAll("companyIds").map(String);const all=String(formData.get("applyToAll"))==="true";if(!z.string().uuid().safeParse(planId).success||!["percentage","fixed"].includes(type)||!Number.isFinite(amount)||amount<0||!effectiveAt||!reason)redirect("/master/planos/reajustes?erro=Preencha os dados do reajuste");const {data:subs}=await admin.from("company_subscriptions").select("company_id,contracted_price").eq("plan_id",planId);const targets=(subs||[]).filter(s=>all||selected.includes(s.company_id));if(!targets.length)redirect("/master/planos/reajustes?erro=Selecione ao menos um cliente");const {data:adjustment,error}=await admin.from("subscription_price_adjustments").insert({plan_id:planId,adjustment_type:type,value:amount,effective_at:new Date(effectiveAt).toISOString(),reason,created_by:user.id}).select("id").single();if(error||!adjustment)redirect(`/master/planos/reajustes?erro=${encodeURIComponent(error?.message||"Não foi possível registrar")}`);const rows=targets.map(s=>{const previous=Number(s.contracted_price||0);return {adjustment_id:adjustment.id,company_id:s.company_id,previous_price:previous,new_price:type==="percentage"?Number((previous*(1+amount/100)).toFixed(2)):amount};});const {error:itemError}=await admin.from("subscription_price_adjustment_items").insert(rows);if(itemError)redirect(`/master/planos/reajustes?erro=${encodeURIComponent(itemError.message)}`);revalidatePath("/master/planos");revalidatePath("/master/planos/reajustes");revalidatePath("/master/empresas");redirect("/master/planos/reajustes?sucesso=Reajuste agendado e registrado no histórico")}
