"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requirePlatformStaff } from "@/lib/master/auth";
import { moduleLabels } from "@/lib/billing/plans";

const schema=z.object({id:z.string().uuid(),name:z.string().trim().min(2).max(80),description:z.string().max(500),monthlyPrice:z.union([z.literal(""),z.coerce.number().min(0)]),status:z.enum(["active","inactive"]),visibility:z.enum(["public","hidden","internal"]),trialDays:z.coerce.number().int().min(0).max(365),productLimit:z.union([z.literal(""),z.coerce.number().int().min(0)]),orderLimit:z.union([z.literal(""),z.coerce.number().int().min(0)])});
export async function updatePlan(formData:FormData){const {admin}=await requirePlatformStaff("master");const parsed=schema.safeParse({id:formData.get("id"),name:formData.get("name"),description:formData.get("description")||"",monthlyPrice:formData.get("monthlyPrice")||"",status:formData.get("status"),visibility:formData.get("visibility"),trialDays:formData.get("trialDays"),productLimit:formData.get("productLimit")||"",orderLimit:formData.get("orderLimit")||""});if(!parsed.success)redirect("/master/planos?erro=Dados inválidos");const v=parsed.data;const {error}=await admin.from("subscription_plans").update({name:v.name,description:v.description||null,monthly_price:v.monthlyPrice===""?null:v.monthlyPrice,is_active:v.status==="active",visibility:v.visibility,trial_days:v.trialDays,product_limit:v.productLimit===""?null:v.productLimit,order_limit:v.orderLimit===""?null:v.orderLimit,updated_at:new Date().toISOString()}).eq("id",v.id);if(error)redirect(`/master/planos?erro=${encodeURIComponent(error.message)}`);revalidatePath("/master/planos");revalidatePath("/master/empresas")}
export async function updatePlanFeatures(formData:FormData){const {admin}=await requirePlatformStaff("master");const planId=String(formData.get("planId")||"");if(!z.string().uuid().safeParse(planId).success)redirect("/master/planos?erro=Plano inválido");const selected=formData.getAll("features").map(String);const rows=Object.keys(moduleLabels).map(moduleKey=>({plan_id:planId,module_key:moduleKey,enabled:selected.includes(moduleKey),updated_at:new Date().toISOString()}));const {error}=await admin.from("plan_entitlements").upsert(rows,{onConflict:"plan_id,module_key"});if(error)redirect(`/master/planos?erro=${encodeURIComponent(error.message)}`);revalidatePath("/master/planos")}

