import Link from "next/link";
import { Cable, CirclePause, CirclePlay, Pencil, Printer, Usb } from "lucide-react";
import { requireModule } from "@/lib/auth/current-company";
import { savePrinter, togglePrinter } from "./actions";
import { DeletePrinterButton } from "./delete-printer-button";
import { PrinterTestButton } from "./printer-test-button";
import { ConnectorDownloadButton } from "./connector-download-button";

type PrinterRow = { id:string; name:string; brand:string|null; model:string|null; connection_type:"usb"|"network"|"bluetooth"; paper_width:number; windows_printer_name:string; sector:"kitchen"|"counter"|"bar"|"delivery"; copies:number; auto_print:boolean; print_customer:boolean; print_address:boolean; print_payment:boolean; status:"active"|"paused"; last_print_at:string|null };
const sectorLabels = { kitchen:"Cozinha", counter:"Balcão", bar:"Bar", delivery:"Entrega" };

export default async function PrinterSettingsPage({ searchParams }: { searchParams:Promise<{ erro?:string; sucesso?:string; editar?:string }> }) {
  const query = await searchParams;
  const { supabase } = await requireModule("settings");
  const { data, error } = await supabase.from("thermal_printers").select("id,name,brand,model,connection_type,paper_width,windows_printer_name,sector,copies,auto_print,print_customer,print_address,print_payment,status,last_print_at").order("created_at");
  const printers = (data || []) as PrinterRow[];
  const editing = printers.find((printer) => printer.id === query.editar);
  return <main className="mx-auto max-w-5xl space-y-6">
    <header><p className="text-sm font-bold text-emerald-700">Equipamentos da loja</p><h1 className="text-3xl font-bold">Impressoras térmicas</h1><p className="mt-2 text-gray-600">Cadastre as impressoras usadas para pedidos, cozinha, balcão e entregas.</p></header>
    {query.erro && <div className="rounded-xl bg-red-50 p-4 text-red-700">{query.erro}</div>}{query.sucesso && <div className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{query.sucesso}</div>}{error && <div className="rounded-xl bg-red-50 p-4 text-red-700">Não foi possível carregar: {error.message}</div>}
    <form key={editing?.id || "new-printer"} action={savePrinter} className="rounded-2xl border bg-white p-5 shadow-sm sm:p-6">
      {editing && <input type="hidden" name="id" value={editing.id}/>}<div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Printer/></span><div><h2 className="text-xl font-bold">{editing ? "Editar impressora" : "Adicionar impressora"}</h2><p className="text-sm text-gray-500">Para a impressora informada, use USB e papel de 80 mm.</p></div></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        <label className="text-sm font-semibold">Nome para identificação<input name="name" required minLength={2} maxLength={80} defaultValue={editing?.name || "Impressora da cozinha"} className="mt-1 w-full rounded-xl border px-3 py-3"/></label>
        <label className="text-sm font-semibold">Nome da impressora no Windows<input name="windowsPrinterName" required maxLength={160} defaultValue={editing?.windows_printer_name || ""} placeholder="Ex.: POS-80C" className="mt-1 w-full rounded-xl border px-3 py-3"/></label>
        <label className="text-sm font-semibold">Marca<input name="brand" maxLength={80} defaultValue={editing?.brand || ""} placeholder="Ex.: Elgin, Epson, Bematech" className="mt-1 w-full rounded-xl border px-3 py-3"/></label>
        <label className="text-sm font-semibold">Modelo<input name="model" maxLength={80} defaultValue={editing?.model || ""} placeholder="Modelo informado na etiqueta" className="mt-1 w-full rounded-xl border px-3 py-3"/></label>
        <label className="text-sm font-semibold">Conexão<select name="connectionType" defaultValue={editing?.connection_type || "usb"} className="mt-1 w-full rounded-xl border bg-white px-3 py-3"><option value="usb">USB</option><option value="network">Rede / Wi-Fi</option><option value="bluetooth">Bluetooth</option></select></label>
        <label className="text-sm font-semibold">Largura do papel<select name="paperWidth" defaultValue={editing?.paper_width || 80} className="mt-1 w-full rounded-xl border bg-white px-3 py-3"><option value="80">80 mm</option><option value="58">58 mm</option></select></label>
        <label className="text-sm font-semibold">Setor<select name="sector" defaultValue={editing?.sector || "kitchen"} className="mt-1 w-full rounded-xl border bg-white px-3 py-3"><option value="kitchen">Cozinha</option><option value="counter">Balcão</option><option value="bar">Bar</option><option value="delivery">Entrega</option></select></label>
        <label className="text-sm font-semibold">Número de vias<input type="number" name="copies" min={1} max={5} defaultValue={editing?.copies || 1} className="mt-1 w-full rounded-xl border px-3 py-3"/></label>
      </div>
      <div className="mt-5 grid gap-3 rounded-xl bg-gray-50 p-4 sm:grid-cols-2"><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" name="autoPrint" defaultChecked={editing?.auto_print ?? false} className="h-5 w-5 accent-emerald-700"/>Imprimir automaticamente{editing && <span className={`ml-auto rounded-full px-2 py-1 text-xs ${editing.auto_print ? "bg-emerald-100 text-emerald-800" : "bg-gray-200 text-gray-600"}`}>{editing.auto_print ? "Ativa" : "Desativada"}</span>}</label><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" name="printCustomer" defaultChecked={editing?.print_customer ?? true} className="h-5 w-5 accent-emerald-700"/>Dados do cliente</label><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" name="printAddress" defaultChecked={editing?.print_address ?? true} className="h-5 w-5 accent-emerald-700"/>Endereço</label><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" name="printPayment" defaultChecked={editing?.print_payment ?? true} className="h-5 w-5 accent-emerald-700"/>Valores e pagamento</label></div>
      <div className="mt-5 flex flex-wrap gap-3"><button className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">{editing ? "Salvar alterações" : "Adicionar impressora"}</button>{editing && <><ConnectorDownloadButton printerId={editing.id}/><Link href="/configuracoes/impressoras" className="rounded-xl border px-5 py-3 font-bold">Cancelar edição</Link></>}</div>
    </form>
    <section className="space-y-3"><h2 className="text-xl font-bold">Impressoras cadastradas</h2>{printers.length === 0 ? <div className="rounded-2xl border border-dashed bg-white p-8 text-center text-gray-500"><Usb className="mx-auto mb-3"/>Nenhuma impressora cadastrada.</div> : printers.map((printer) => <article key={printer.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Cable/></span><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{printer.name}</h3><span className={`rounded-full px-2 py-1 text-xs font-bold ${printer.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-gray-100 text-gray-600"}`}>{printer.status === "active" ? "Ativa" : "Pausada"}</span></div><p className="text-sm text-gray-500">{printer.brand || "Marca não informada"} {printer.model || ""} · {printer.connection_type.toUpperCase()} · {printer.paper_width} mm · {sectorLabels[printer.sector]}</p><p className="mt-1 text-xs text-gray-500">Windows: {printer.windows_printer_name} · {printer.copies} {printer.copies === 1 ? "via" : "vias"}{printer.auto_print ? " · Automática" : " · Manual"}</p></div></div><div className="flex flex-wrap gap-2"><PrinterTestButton printerName={printer.name} width={printer.paper_width}/><Link href={`/configuracoes/impressoras?editar=${printer.id}`} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-bold"><Pencil size={16}/>Editar</Link><form action={togglePrinter}><input type="hidden" name="id" value={printer.id}/><input type="hidden" name="status" value={printer.status === "active" ? "paused" : "active"}/><button className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-bold">{printer.status === "active" ? <CirclePause size={16}/> : <CirclePlay size={16}/>} {printer.status === "active" ? "Pausar" : "Ativar"}</button></form><DeletePrinterButton id={printer.id}/></div></div></article>)}</section>
    <aside className="rounded-2xl border border-orange-200 bg-orange-50 p-5 text-sm text-orange-950"><strong>Impressão automática USB:</strong> a configuração fica salva no MercadoFood. Para imprimir sem abrir a janela do navegador, será necessário instalar o Conector MercadoFood no computador da loja.</aside>
  </main>;
}
