"use client";

import { useMemo, useState } from "react";
import { PrintOrderButton } from "./print-order-button";
import { assignOrderDriver, updateOrderStatus } from "./actions";

export type OrderRow = {
  id: string; order_number: number; branch_id: string; assigned_driver_id?: string | null; customer_id: string | null; customer_name: string | null; customer_phone: string | null;
  status: string; service_type: string; subtotal: number | string; discount_amount: number | string; delivery_fee: number | string;
  total: number | string; coupon_code: string | null; loyalty_points_redeemed: number; payment_method: string | null;
  payment_status: string; change_amount: number | string; notes: string | null; delivery_address: Record<string, string> | null;
  created_at: string; order_items: Array<{ product_name: string; quantity: number; unit_price: number | string; total_price: number | string }>;
  customer?: { name: string; phone: string; cpf?: string | null; address?: Record<string, string> | null; total_orders: number; total_spent: number | string; last_order_at: string | null } | null;
};

type Printer = { name: string; paper_width: number; copies: number; print_customer: boolean; print_address: boolean; print_payment: boolean; sector: string; status: string } | null;
const labels: Record<string,string> = { new:"Novo", accepted:"Aceito", preparing:"Em preparo", ready:"Pronto", out_for_delivery:"Em entrega", delivered:"Entregue", canceled:"Cancelado" };
const paymentLabels: Record<string,string> = { pending:"Pagamento pendente", processing:"Pagamento em análise", under_review:"Pagamento em análise", paid:"Pago", canceled:"Pagamento cancelado", refunded:"Estornado" };
const next: Record<string,string | undefined> = { new:"accepted", accepted:"preparing", preparing:"ready", ready:"out_for_delivery", out_for_delivery:"delivered" };
function money(value: number | string | null | undefined) { return new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL" }).format(Number(value || 0)); }
function dateTime(value: string | null | undefined) { return value ? new Date(value).toLocaleString("pt-BR") : "—"; }
function addressText(value: Record<string,string> | null | undefined) { return value ? [value.street,value.number,value.complement,value.neighborhood,value.city,value.reference].filter(Boolean).join(", ") || "Não informado" : "Não informado"; }

export function OrderWorkspace({ orders, companyName, printer, customerOrders, drivers }: { orders: OrderRow[]; companyName: string; printer: Printer; customerOrders: OrderRow[]; drivers: Array<{id:string;name:string;branch_id:string|null;availability_status:string}> }) {
  const [selectedId, setSelectedId] = useState(orders[0]?.id || "");
  const selected = orders.find(order => order.id === selectedId) || orders[0];
  const purchases = useMemo(() => selected ? customerOrders.filter(order => selected.customer_id ? order.customer_id === selected.customer_id : Boolean(selected.customer_phone) && order.customer_phone === selected.customer_phone) : [], [customerOrders, selected]);
  const customer = selected?.customer;
  const completed = purchases.filter(order => order.status === "delivered");
  const totalSpent = customer?.total_spent ?? completed.reduce((sum, order) => sum + Number(order.total || 0), 0);
  const totalOrders = customer?.total_orders ?? completed.length;
  const ticket = Number(totalOrders) ? Number(totalSpent) / Number(totalOrders) : 0;

  if (!orders.length) return <div className="rounded-2xl border bg-white p-8 text-gray-500">Nenhuma pendência operacional. Os pedidos concluídos estão no Histórico.</div>;
  return <section className="grid min-h-0 gap-5 lg:h-[calc(100vh-14rem)] lg:min-h-[420px] lg:max-h-[760px] lg:grid-cols-[minmax(0,1.45fr)_minmax(320px,.8fr)]">
    <div className="mf-scroll-pane h-[55vh] min-h-[320px] overflow-y-scroll overscroll-contain rounded-2xl border bg-white p-3 shadow-sm sm:p-4 lg:h-full lg:min-h-0" aria-label="Fila operacional de pedidos"><div className="sticky top-0 z-10 -mx-1 mb-3 rounded-xl border bg-white/95 px-3 py-2 backdrop-blur"><p className="text-sm font-bold text-emerald-700">Fila de pedidos</p><p className="text-xs text-gray-500">Role somente esta coluna para ver os demais pedidos.</p></div><div className="space-y-3">
      {orders.map(order => { const target = next[order.status]; const selectedOrder = selected?.id === order.id; return <article key={order.id} className={`rounded-2xl border p-4 transition ${selectedOrder ? "border-emerald-600 ring-2 ring-emerald-100" : "bg-white"}`}>
        <button type="button" onClick={() => setSelectedId(order.id)} className="w-full text-left" aria-pressed={selectedOrder}><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><p className="text-sm font-semibold text-emerald-700">Pedido #{order.order_number}</p><h2 className="truncate text-xl font-bold">{order.customer_name || "Cliente"}</h2><p className="text-sm text-gray-500">{order.customer_phone || "Sem telefone"} • {order.service_type}</p><p className="mt-2 text-sm">{(order.order_items || []).map(item => `${item.quantity}× ${item.product_name}`).join(" • ") || "Itens não carregados"}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-800">{labels[order.status] || order.status}</span><span className={`rounded-full px-3 py-2 text-sm font-semibold ${order.payment_status === "paid" ? "bg-blue-50 text-blue-800" : "bg-orange-50 text-orange-800"}`}>{paymentLabels[order.payment_status] || order.payment_status}</span><strong>{money(order.total)}</strong></div></div></button>
        <div className="mt-4 flex flex-wrap items-center gap-2 border-t pt-3"><PrintOrderButton order={order as never} companyName={companyName} printer={printer}/>{order.status === "ready" && order.service_type === "delivery" ? <details className="relative"><summary className="cursor-pointer list-none rounded-xl bg-emerald-700 px-4 py-2 font-semibold text-white">Enviar para entrega</summary><form action={assignOrderDriver} className="absolute left-0 z-20 mt-2 w-80 space-y-3 rounded-xl border bg-white p-4 shadow-xl"><input type="hidden" name="orderId" value={order.id}/><label className="block text-xs font-semibold">Entregador ativo desta loja<select name="driverId" required className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="">Selecione</option>{drivers.filter(driver=>!driver.branch_id||driver.branch_id===order.branch_id).map(driver=><option key={driver.id} value={driver.id}>{driver.name}</option>)}</select></label><button className="w-full rounded-lg bg-emerald-700 px-3 py-2 font-bold text-white">Confirmar atribuição</button></form></details> : target && <form action={updateOrderStatus}><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="status" value={target}/><button className="rounded-xl bg-emerald-700 px-4 py-2 font-semibold text-white">Avançar para {labels[target]}</button></form>}{order.status !== "delivered" && <details className="relative"><summary className="cursor-pointer list-none rounded-xl border border-red-200 px-4 py-2 font-semibold text-red-700">Cancelar</summary><form action={updateOrderStatus} className="absolute right-0 z-20 mt-2 w-72 space-y-2 rounded-xl border bg-white p-3 shadow-xl"><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="status" value="canceled"/><label className="block text-xs font-semibold">Motivo do cancelamento<textarea name="cancellationReason" required className="mt-1 min-h-20 w-full rounded-lg border p-2 text-sm"/></label><button className="w-full rounded-lg bg-red-600 px-3 py-2 font-bold text-white">Confirmar cancelamento</button></form></details>}</div>
      </article>; })}
    </div></div>
    {selected && <aside className="mf-scroll-pane h-[55vh] min-h-[320px] overflow-y-scroll overscroll-contain rounded-2xl border bg-white p-5 shadow-sm lg:h-full lg:min-h-0" aria-label="Dados do cliente selecionado"><p className="text-sm font-bold uppercase tracking-wide text-emerald-700">Dados do cliente</p><p className="text-xs text-gray-500">Este painel possui rolagem independente.</p><h2 className="mt-2 text-2xl font-bold">{customer?.name || selected.customer_name || "Cliente"}</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-1 2xl:grid-cols-2"><Metric label="Telefone" value={customer?.phone || selected.customer_phone || "Não informado"}/><Metric label="CPF" value={customer?.cpf || "Não informado"}/><Metric label="Endereço" value={addressText(customer?.address || selected.delivery_address)} wide/><Metric label="Total de pedidos" value={String(totalOrders)}/><Metric label="Total gasto" value={money(totalSpent)}/><Metric label="Ticket médio" value={money(ticket)}/><Metric label="Última compra" value={dateTime(customer?.last_order_at || purchases[0]?.created_at)} wide/></dl><div className="mt-6 border-t pt-5"><h3 className="font-bold">Histórico de compras</h3><p className="text-xs text-gray-500">A lista abaixo também possui rolagem própria.</p><div className="mf-scroll-pane mt-3 h-56 space-y-2 overflow-y-scroll overscroll-contain pr-2" aria-label="Histórico de compras do cliente">{purchases.map(order => <article key={order.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><div><strong>Pedido #{order.order_number}</strong><p className="text-xs text-gray-500">{dateTime(order.created_at)} • {labels[order.status] || order.status}</p></div><strong>{money(order.total)}</strong></div></article>)}{!purchases.length && <p className="rounded-xl bg-gray-50 p-4 text-sm text-gray-500">Nenhuma compra anterior identificada.</p>}</div></div></aside>}
  </section>;
}
function Metric({ label, value, wide = false }: { label: string; value: string; wide?: boolean }) { return <div className={`rounded-xl bg-gray-50 p-3 ${wide ? "sm:col-span-2 lg:col-span-1 2xl:col-span-2" : ""}`}><dt className="text-xs font-semibold uppercase text-gray-500">{label}</dt><dd className="mt-1 break-words font-semibold">{value}</dd></div>; }


