import Link from "next/link";
import { requirePlanModule } from "@/lib/auth/current-company";
import { createOption, createOptionGroup, toggleGroup, toggleOption, updateOption, updateOptionGroup } from "./actions";
import { DeleteGroupForm, DeleteOptionForm } from "./delete-controls";

const money = (value: number | string | null) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value || 0));

export default async function ComplementosPage({ params, searchParams }: { params: Promise<{ productId: string }>; searchParams: Promise<{ erro?: string; sucesso?: string }> }) {
  const { productId } = await params;
  const query = await searchParams;
  const { supabase, company } = await requirePlanModule("products");
  const [{ data: product }, { data: groups }] = await Promise.all([
    supabase.from("products").select("id, name, base_price").eq("id", productId).eq("company_id", company.id).single(),
    supabase.from("product_option_groups").select("id, name, description, group_type, min_selection, max_selection, free_selection, is_active, product_options(id, name, price_delta, max_quantity, is_active)").eq("product_id", productId).eq("company_id", company.id).order("sort_order"),
  ]);

  if (!product) return <main className="rounded-2xl border bg-white p-8"><h1 className="text-2xl font-bold">Produto não encontrado</h1><Link href="/produtos" className="mt-4 inline-block text-emerald-700">Voltar para produtos</Link></main>;

  return <main className="space-y-6">
    <header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><Link href="/produtos" className="text-sm font-semibold text-emerald-700">← Produtos</Link><p className="mt-2 text-sm font-semibold text-orange-600">Complementos e adicionais</p><h1 className="text-3xl font-bold">{product.name}</h1><p className="text-gray-500">Preço base {money(product.base_price)}. Configure as escolhas extras que aparecerão para o cliente antes de adicionar o produto ao carrinho.</p></div></header>
    {query.erro && <div className="rounded-xl bg-red-50 p-4 text-red-700">{query.erro}</div>}
    {query.sucesso && <div className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{query.sucesso}</div>}

    <section className="grid gap-5 xl:grid-cols-[380px_1fr]">
      <form action={createOptionGroup} className="h-fit rounded-2xl border bg-white p-5 shadow-sm">
        <input type="hidden" name="productId" value={product.id}/><h2 className="text-xl font-bold">Novo grupo de escolhas</h2>
        <p className="mt-1 text-sm text-gray-500">Crie um conjunto como “Adicionais”, “Escolha o tamanho” ou “Molhos”. Depois, cadastre as opções e seus valores.</p>
        <label className="mt-4 block text-sm font-semibold">Nome do grupo</label><input name="name" required placeholder="Ex.: Adicionais" className="mt-1 w-full rounded-xl border p-3"/>
        <label className="mt-3 block text-sm font-semibold">Orientação para o cliente</label><input name="description" placeholder="Ex.: Escolha até 3 adicionais" className="mt-1 w-full rounded-xl border p-3"/>
        <label className="mt-3 block text-sm font-semibold">Tipo de escolha</label><select name="groupType" className="mt-1 w-full rounded-xl border p-3"><option value="single">Uma opção</option><option value="multiple">Várias opções</option><option value="quantity">Quantidade por opção</option></select>
        <div className="mt-3 grid grid-cols-3 gap-2"><div><label className="block text-xs font-semibold">Mínimo</label><input name="minSelection" type="number" min="0" defaultValue="0" className="mt-1 w-full rounded-xl border p-3"/></div><div><label className="block text-xs font-semibold">Máximo</label><input name="maxSelection" type="number" min="1" defaultValue="1" className="mt-1 w-full rounded-xl border p-3"/></div><div><label className="block text-xs font-semibold">Grátis</label><input name="freeSelection" type="number" min="0" defaultValue="0" className="mt-1 w-full rounded-xl border p-3"/></div></div>
        <button className="mt-5 w-full rounded-xl bg-emerald-700 py-3 font-bold text-white">Criar grupo de escolhas</button>
      </form>

      <div className="space-y-4">
        {!groups?.length && <div className="rounded-2xl border bg-white p-8 text-center text-gray-500">Nenhum complemento ou adicional criado para este produto.</div>}
        {groups?.map((group: any) => <article key={group.id} className="rounded-2xl border bg-white p-5 shadow-sm">
          <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-bold">{group.name}</h2><span className={`rounded-full px-2 py-1 text-xs font-semibold ${group.is_active ? "bg-emerald-50 text-emerald-700" : "bg-gray-100 text-gray-500"}`}>{group.is_active ? "Ativo" : "Pausado"}</span></div><p className="text-sm text-gray-500">{group.group_type === "single" ? "Escolha única" : group.group_type === "quantity" ? "Quantidade por opção" : "Múltipla escolha"} • mínimo {group.min_selection} • máximo {group.max_selection} • {group.free_selection || 0} grátis</p><p className="text-sm text-gray-600">{group.description}</p></div><div className="flex flex-wrap gap-2"><form action={toggleGroup}><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="groupId" value={group.id}/><input type="hidden" name="active" value={String(!group.is_active)}/><button className="rounded-xl border px-3 py-2 text-sm font-semibold">{group.is_active ? "Pausar" : "Ativar"}</button></form><DeleteGroupForm productId={product.id} groupId={group.id} groupName={group.name}/></div></div>
          <details className="mt-4 rounded-xl border border-emerald-100 bg-emerald-50/40 p-4"><summary className="cursor-pointer font-bold text-emerald-800">Editar informações do grupo</summary><form action={updateOptionGroup} className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="groupId" value={group.id}/><label className="text-sm font-semibold">Nome<input name="name" required defaultValue={group.name} className="mt-1 w-full rounded-xl border bg-white p-3"/></label><label className="text-sm font-semibold">Tipo<select name="groupType" defaultValue={group.group_type} className="mt-1 w-full rounded-xl border bg-white p-3"><option value="single">Uma opção</option><option value="multiple">Várias opções</option><option value="quantity">Quantidade por opção</option></select></label><label className="text-sm font-semibold md:col-span-2">Orientação<input name="description" defaultValue={group.description || ""} className="mt-1 w-full rounded-xl border bg-white p-3"/></label><label className="text-sm font-semibold">Mínimo<input name="minSelection" type="number" min="0" defaultValue={group.min_selection} className="mt-1 w-full rounded-xl border bg-white p-3"/></label><label className="text-sm font-semibold">Máximo<input name="maxSelection" type="number" min="1" defaultValue={group.max_selection} className="mt-1 w-full rounded-xl border bg-white p-3"/></label><label className="text-sm font-semibold">Quantidade grátis<input name="freeSelection" type="number" min="0" defaultValue={group.free_selection || 0} className="mt-1 w-full rounded-xl border bg-white p-3"/></label><button className="self-end rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white">Salvar edição do grupo</button></form></details>
          <div className="mt-4 space-y-2">{(group.product_options || []).map((option: any) => <details key={option.id} className="rounded-xl bg-gray-50 p-3"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between gap-3"><div><strong>{option.name}</strong><p className="text-xs text-gray-500">Valor: {Number(option.price_delta) > 0 ? `+ ${money(option.price_delta)}` : "sem acréscimo"} • até {option.max_quantity || 1} • {option.is_active ? "Ativa" : "Pausada"}</p></div><span className="text-sm font-semibold text-emerald-700">Editar</span></div></summary><div className="mt-3 border-t pt-3"><form action={updateOption} className="grid gap-3 md:grid-cols-[1fr_180px_150px_auto]"><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="optionId" value={option.id}/><label className="text-xs font-semibold text-gray-700">Nome do complemento<input name="name" required defaultValue={option.name} className="mt-1 w-full rounded-xl border bg-white p-3 text-base font-normal"/></label><label className="text-xs font-semibold text-gray-700">Valor do complemento (R$)<div className="relative mt-1"><span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-sm font-bold text-emerald-700">R$</span><input name="priceDelta" inputMode="decimal" required defaultValue={Number(option.price_delta || 0).toFixed(2).replace(".", ",")} className="w-full rounded-xl border bg-white py-3 pl-10 pr-3 text-base font-normal"/></div></label><label className="text-xs font-semibold text-gray-700">Quantidade máxima<input name="maxQuantity" type="number" min="1" defaultValue={option.max_quantity || 1} className="mt-1 w-full rounded-xl border bg-white p-3 text-base font-normal"/></label><button className="self-end rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white">Salvar</button></form><div className="mt-3 flex gap-4"><form action={toggleOption}><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="optionId" value={option.id}/><input type="hidden" name="active" value={String(!option.is_active)}/><button className="text-sm font-semibold text-emerald-700">{option.is_active ? "Pausar opção" : "Ativar opção"}</button></form><DeleteOptionForm productId={product.id} optionId={option.id} optionName={option.name}/></div></div></details>)}</div>
          <form action={createOption} className="mt-4 grid gap-3 border-t pt-4 md:grid-cols-[1fr_180px_150px_auto]"><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="groupId" value={group.id}/><label className="text-xs font-semibold text-gray-700">Nome do complemento<input name="name" required placeholder="Ex.: Bacon extra" className="mt-1 w-full rounded-xl border p-3 text-base font-normal"/></label><label className="text-xs font-semibold text-gray-700">Valor do complemento (R$)<div className="relative mt-1"><span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-sm font-bold text-emerald-700">R$</span><input name="priceDelta" inputMode="decimal" required defaultValue="0,00" placeholder="0,00" className="w-full rounded-xl border py-3 pl-10 pr-3 text-base font-normal"/></div></label><label className="text-xs font-semibold text-gray-700">Quantidade máxima<input name="maxQuantity" type="number" min="1" defaultValue="1" className="mt-1 w-full rounded-xl border p-3 text-base font-normal"/></label><button className="self-end rounded-xl bg-orange-500 px-4 py-3 font-bold text-white">Adicionar opção</button></form>
        </article>)}
      </div>
    </section>
  </main>;
}
