import Link from "next/link";
import { Archive, Check, MessageSquareText, Send, Star } from "lucide-react";
import { requirePlanModule } from "@/lib/auth/current-company";
import { archiveMessage, markMessageRead, replyToMessage } from "./actions";
import { DeleteMessageButton } from "./delete-message-button";

const categoryLabels: Record<string,string> = { feedback:"Feedback", suggestion:"Sugestão", complaint:"Reclamação", praise:"Elogio" };
const statusLabels: Record<string,string> = { new:"Nova", read:"Lida", replied:"Respondida", archived:"Arquivada" };

export default async function MessagesPage({ searchParams }: { searchParams: Promise<{ status?:string; category?:string; erro?:string; sucesso?:string }> }) {
  const query = await searchParams;
  const { supabase, company, role } = await requirePlanModule("messages");
  let request = supabase.from("customer_messages").select("*").eq("company_id",company.id).order("created_at",{ascending:false}).limit(100);
  if (["new","read","replied","archived"].includes(query.status || "")) request = request.eq("status",query.status!);
  if (["feedback","suggestion","complaint","praise"].includes(query.category || "")) request = request.eq("category",query.category!);
  const { data: messages, error } = await request;
  const list = messages || [];
  const unread = list.filter(item => item.status === "new").length;
  const rated = list.filter(item => Number(item.rating) > 0);
  const average = rated.length ? rated.reduce((sum,item)=>sum+Number(item.rating),0)/rated.length : 0;

  return <div className="space-y-6">
    <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold text-emerald-700">Relacionamento com o cliente</p><h1 className="text-3xl font-black">Mensagens e avaliações</h1><p className="text-gray-500">Receba feedbacks, sugestões, reclamações e elogios enviados pelo cardápio da {company.name}.</p></div><Link href={`/cardapio/${company.slug}`} target="_blank" className="rounded-xl bg-orange-500 px-4 py-3 text-center font-bold text-white">Abrir cardápio do cliente</Link></header>
    {query.sucesso && <p className="rounded-xl bg-emerald-50 p-4 font-semibold text-emerald-800">{query.sucesso}</p>}{query.erro && <p className="rounded-xl bg-red-50 p-4 font-semibold text-red-700">{query.erro}</p>}{error && <p className="rounded-xl bg-amber-50 p-4 font-semibold text-amber-900">A central precisa da migration 0032 no Supabase: {error.message}</p>}
    <section className="grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border bg-white p-5 shadow-sm"><MessageSquareText className="text-emerald-700"/><p className="mt-3 text-sm text-gray-500">Mensagens exibidas</p><strong className="text-3xl">{list.length}</strong></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><span className="grid h-6 w-6 place-items-center rounded-full bg-orange-500 text-xs font-black text-white">!</span><p className="mt-3 text-sm text-gray-500">Não lidas</p><strong className="text-3xl">{unread}</strong></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><Star className="fill-amber-400 text-amber-400"/><p className="mt-3 text-sm text-gray-500">Avaliação média</p><strong className="text-3xl">{average ? average.toFixed(1) : "—"}</strong><span className="text-sm text-gray-500"> / 5</span></article></section>
    <section className="flex flex-wrap gap-2 rounded-2xl border bg-white p-4"><Link href="/mensagens" className={`rounded-full px-4 py-2 text-sm font-bold ${!query.status&&!query.category?"bg-emerald-700 text-white":"bg-gray-100"}`}>Todas</Link>{Object.entries(statusLabels).map(([value,label])=><Link key={value} href={`/mensagens?status=${value}`} className={`rounded-full px-4 py-2 text-sm font-bold ${query.status===value?"bg-orange-500 text-white":"bg-gray-100"}`}>{label}</Link>)}{Object.entries(categoryLabels).map(([value,label])=><Link key={value} href={`/mensagens?category=${value}`} className={`rounded-full px-4 py-2 text-sm font-bold ${query.category===value?"bg-orange-500 text-white":"bg-gray-100"}`}>{label}</Link>)}</section>
    <section className="space-y-4">{list.map(item=><article key={item.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${item.status==="new"?"border-l-4 border-l-orange-500":""}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-lg">{item.customer_name || "Cliente anônimo"}</strong><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-800">{categoryLabels[item.category]}</span><span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-bold">{statusLabels[item.status]}</span></div><div className="mt-2 flex items-center gap-1" aria-label={`${item.rating} de 5 estrelas`}>{[1,2,3,4,5].map(star=><Star key={star} size={18} className={star<=item.rating?"fill-amber-400 text-amber-400":"text-gray-300"}/>)}</div></div><div className="text-left text-xs text-gray-500 sm:text-right"><p>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(item.created_at))}</p>{item.customer_contact && <a href={`https://wa.me/${String(item.customer_contact).replace(/\D/g,"")}`} target="_blank" className="mt-1 block font-bold text-emerald-700">{item.customer_contact}</a>}</div></div><p className="mt-4 whitespace-pre-wrap rounded-xl bg-gray-50 p-4 text-gray-800">{item.message}</p>{item.owner_reply && <div className="mt-3 rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-xs font-bold uppercase text-emerald-800">Resposta registrada</p><p className="mt-1 whitespace-pre-wrap">{item.owner_reply}</p></div>}
      <div className="mt-4 flex flex-wrap gap-2">{item.status==="new"&&<form action={markMessageRead}><input type="hidden" name="id" value={item.id}/><button className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold hover:bg-gray-50"><Check size={16}/>Marcar como lida</button></form>}<form action={archiveMessage}><input type="hidden" name="id" value={item.id}/><button className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold hover:bg-gray-50"><Archive size={16}/>Arquivar</button></form>{["owner","manager"].includes(role)&&<DeleteMessageButton id={item.id}/>}</div>
      <form action={replyToMessage} className="mt-4 flex flex-col gap-2 sm:flex-row"><input type="hidden" name="id" value={item.id}/><textarea name="reply" defaultValue={item.owner_reply || ""} required rows={2} maxLength={2000} placeholder="Registre a resposta dada ao cliente" className="min-h-20 flex-1 rounded-xl border px-3 py-2"/><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white"><Send size={17}/>Salvar resposta</button></form><p className="mt-2 text-xs text-gray-500">A resposta fica registrada. Use o WhatsApp acima para enviá-la ao cliente quando houver contato.</p></article>)}{!list.length&&!error&&<div className="rounded-2xl border border-dashed bg-white p-12 text-center"><MessageSquareText className="mx-auto text-gray-300" size={44}/><h2 className="mt-3 text-xl font-bold">Nenhuma mensagem nesta seleção</h2><p className="text-gray-500">As novas avaliações aparecerão aqui.</p></div>}</section>
  </div>;
}
