import Link from "next/link";
import { Bot, MessageCircle, Send, UserRound } from "lucide-react";
import { sendWhatsAppReply, setWhatsAppConversationMode } from "./actions";

type Conversation = { id:string; customer_name:string|null; customer_phone:string; status:string; unread_count:number; last_message_at:string };
type Message = { id:string; conversation_id:string; direction:string; sender_type:string; body:string; delivery_status:string; created_at:string };

export function WhatsAppConversations({ connected, conversations, messages }: { connected:boolean; conversations:Conversation[]; messages:Message[] }) {
  return <section className="space-y-4">
    <div className="flex flex-col gap-3 rounded-2xl border bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><MessageCircle className="text-emerald-700"/><div><h2 className="text-xl font-bold">Conversas do WhatsApp</h2><p className="text-sm text-gray-500">Mensagens recebidas pelo número conectado.</p></div></div><Link href="/configuracoes/whatsapp" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-center text-sm font-bold text-emerald-800">{connected ? "Configurar chatbot" : "Conectar WhatsApp"}</Link></div>
    {!connected && <div className="rounded-2xl border border-dashed bg-white p-8 text-center text-gray-500">Conecte o WhatsApp em Configurações para receber conversas aqui.</div>}
    {connected && !conversations.length && <div className="rounded-2xl border border-dashed bg-white p-8 text-center text-gray-500">Nenhuma conversa recebida ainda.</div>}
    {conversations.map(conversation => {
      const items = messages.filter(message => message.conversation_id === conversation.id);
      return <details key={conversation.id} open={conversation.unread_count > 0} className="rounded-2xl border bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5"><div><div className="flex flex-wrap items-center gap-2"><strong>{conversation.customer_name || conversation.customer_phone}</strong>{conversation.unread_count > 0 && <span className="rounded-full bg-orange-500 px-2 py-0.5 text-xs font-black text-white">{conversation.unread_count} nova(s)</span>}</div><p className="text-sm text-gray-500">{conversation.customer_phone}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${conversation.status === "bot" ? "bg-emerald-50 text-emerald-700" : "bg-blue-50 text-blue-700"}`}>{conversation.status === "bot" ? "Chatbot atendendo" : conversation.status === "attendant" ? "Atendente" : "Encerrada"}</span></summary><div className="border-t p-5"><div className="max-h-80 space-y-2 overflow-y-auto rounded-2xl bg-gray-50 p-4">{items.map(message => <div key={message.id} className={`flex ${message.direction === "outbound" ? "justify-end" : "justify-start"}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm ${message.direction === "outbound" ? "bg-emerald-700 text-white" : "border bg-white"}`}><p className="whitespace-pre-wrap">{message.body}</p><p className={`mt-1 text-[10px] ${message.direction === "outbound" ? "text-emerald-100" : "text-gray-400"}`}>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(message.created_at))}</p></div></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><form action={setWhatsAppConversationMode}><input type="hidden" name="conversationId" value={conversation.id}/><input type="hidden" name="mode" value="attendant"/><button className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold"><UserRound size={16}/>Assumir conversa</button></form><form action={setWhatsAppConversationMode}><input type="hidden" name="conversationId" value={conversation.id}/><input type="hidden" name="mode" value="bot"/><button className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold"><Bot size={16}/>Devolver ao bot</button></form></div><form action={sendWhatsAppReply} className="mt-3 flex flex-col gap-2 sm:flex-row"><input type="hidden" name="conversationId" value={conversation.id}/><textarea name="body" required maxLength={4000} rows={2} placeholder="Responder pelo WhatsApp" className="min-h-20 flex-1 rounded-xl border p-3"/><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white"><Send size={17}/>Enviar</button></form></div></details>;
    })}
  </section>;
}
