import { getCurrentCompany } from "@/lib/auth/current-company";
import { createCoupon, createPromotion, toggleCoupon, togglePromotion } from "./actions";

function money(v:number|string|null|undefined){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0))}
function date(v:string|null|undefined){return v?new Date(v).toLocaleDateString("pt-BR"):"Sem limite"}

export default async function PromocoesPage({searchParams}:{searchParams:Promise<{erro?:string;sucesso?:string}>}){
  const query=await searchParams;
  const {supabase,company}=await getCurrentCompany();
  const [{data:coupons},{data:promotions},{data:redemptions}]=await Promise.all([
    supabase.from("coupons").select("*").eq("company_id",company.id).order("created_at",{ascending:false}),
    supabase.from("promotions").select("*").eq("company_id",company.id).order("created_at",{ascending:false}),
    supabase.from("coupon_redemptions").select("discount_amount").eq("company_id",company.id),
  ]);
  const activeCoupons=(coupons||[]).filter(c=>c.is_active).length;
  const totalDiscount=(redemptions||[]).reduce((s,r)=>s+Number(r.discount_amount||0),0);
  return <main className="space-y-6">
    <header><p className="text-sm font-semibold text-emerald-700">Vendas e relacionamento</p><h1 className="text-3xl font-bold">Cupons e promoções</h1><p className="text-gray-500">Crie ofertas, controle limites e aplique recompensas no pedido.</p></header>
    {query.erro&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{query.erro}</div>}{query.sucesso&&<div className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{query.sucesso}</div>}
    <section className="grid gap-4 md:grid-cols-3"><Card label="Cupons ativos" value={String(activeCoupons)}/><Card label="Resgates" value={String(redemptions?.length||0)}/><Card label="Descontos concedidos" value={money(totalDiscount)}/></section>
    <section className="grid gap-6 xl:grid-cols-2">
      <form action={createCoupon} className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Novo cupom</h2><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Código<input name="code" required placeholder="BEMVINDO10" className="mt-1 w-full rounded-xl border px-3 py-3 uppercase"/></label><label className="text-sm font-semibold">Nome<input name="name" required placeholder="10% de boas-vindas" className="mt-1 w-full rounded-xl border px-3 py-3"/></label></div><label className="mt-3 block text-sm font-semibold">Descrição</label><input name="description" className="mt-1 w-full rounded-xl border px-3 py-3"/>
      <div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Tipo<select name="discountType" className="mt-1 w-full rounded-xl border px-3 py-3"><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select></label><label className="text-sm font-semibold">Valor<input name="discountValue" type="number" min="0.01" step="0.01" required className="mt-1 w-full rounded-xl border px-3 py-3"/></label></div>
      <div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Pedido mínimo<input name="minimumOrderValue" type="number" min="0" step="0.01" defaultValue="0" className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-sm font-semibold">Desconto máximo<input name="maximumDiscount" type="number" min="0" step="0.01" className="mt-1 w-full rounded-xl border px-3 py-3"/></label></div>
      <div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Início<input name="startsAt" type="datetime-local" className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-sm font-semibold">Fim<input name="endsAt" type="datetime-local" className="mt-1 w-full rounded-xl border px-3 py-3"/></label></div>
      <div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Limite total<input name="usageLimit" type="number" min="1" className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-sm font-semibold">Por cliente<input name="perCustomerLimit" type="number" min="1" defaultValue="1" className="mt-1 w-full rounded-xl border px-3 py-3"/></label></div><button className="mt-4 w-full rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white">Criar cupom</button></form>
      <form action={createPromotion} className="h-fit rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Nova promoção</h2><label className="mt-4 block text-sm font-semibold">Título</label><input name="title" required placeholder="Festival de hambúrguer" className="mt-1 w-full rounded-xl border px-3 py-3"/><label className="mt-3 block text-sm font-semibold">Tipo</label><select name="promotionType" className="mt-1 w-full rounded-xl border px-3 py-3"><option value="offer">Oferta</option><option value="product_discount">Desconto em produto</option><option value="combo">Combo</option><option value="free_delivery">Entrega grátis</option><option value="banner">Banner</option></select><label className="mt-3 block text-sm font-semibold">Descrição</label><textarea name="description" rows={3} className="mt-1 w-full rounded-xl border px-3 py-3"/><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Início<input name="startsAt" type="datetime-local" className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-sm font-semibold">Fim<input name="endsAt" type="datetime-local" className="mt-1 w-full rounded-xl border px-3 py-3"/></label></div><button className="mt-4 w-full rounded-xl border border-emerald-700 px-4 py-3 font-semibold text-emerald-800">Criar promoção</button></form>
    </section>
    <section className="grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Cupons cadastrados</h2><div className="mt-4 space-y-3">{coupons?.map(c=><article key={c.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><strong className="text-lg">{c.code}</strong><p className="text-sm text-gray-500">{c.name}</p><p className="mt-1 text-sm">{c.discount_type==="percentage"?`${c.discount_value}%`:money(c.discount_value)} de desconto • mínimo {money(c.minimum_order_value)}</p><p className="text-xs text-gray-500">Usos {c.usage_count}{c.usage_limit?`/${c.usage_limit}`:""} • até {date(c.ends_at)}</p></div><form action={toggleCoupon}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="active" value={String(c.is_active)}/><button className={`rounded-full px-3 py-2 text-sm font-semibold ${c.is_active?"bg-emerald-50 text-emerald-800":"bg-gray-100 text-gray-600"}`}>{c.is_active?"Ativo":"Inativo"}</button></form></div></article>)}{!coupons?.length&&<p className="rounded-xl bg-gray-50 p-5 text-gray-500">Nenhum cupom.</p>}</div></div>
    <div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Campanhas promocionais</h2><div className="mt-4 space-y-3">{promotions?.map(p=><article key={p.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><strong>{p.title}</strong><p className="text-sm text-gray-500">{p.description||p.promotion_type}</p><p className="text-xs text-gray-500">{date(p.starts_at)} até {date(p.ends_at)}</p></div><form action={togglePromotion}><input type="hidden" name="id" value={p.id}/><input type="hidden" name="active" value={String(p.is_active)}/><button className={`rounded-full px-3 py-2 text-sm font-semibold ${p.is_active?"bg-orange-50 text-orange-700":"bg-gray-100 text-gray-600"}`}>{p.is_active?"Ativa":"Inativa"}</button></form></div></article>)}{!promotions?.length&&<p className="rounded-xl bg-gray-50 p-5 text-gray-500">Nenhuma promoção.</p>}</div></div></section>
  </main>
}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><strong className="mt-1 block text-2xl text-emerald-700">{value}</strong></div>}
