"use client";
import { useActionState } from "react";
import { Clock3, Copy, ShieldCheck } from "lucide-react";
import { generateSupportCode, type SupportCodeState } from "./actions";
const initialState: SupportCodeState={};
export function SupportCodeGenerator(){const [state,action,pending]=useActionState(generateSupportCode,initialState);return <div className="grid gap-6 lg:grid-cols-[1fr_.8fr]">
  <form action={action} className="space-y-5 rounded-2xl border bg-white p-5 shadow-sm"><div><h2 className="text-xl font-bold">Gerar código de atendimento</h2><p className="mt-1 text-sm text-gray-500">O código funciona uma vez e expira automaticamente em 30 minutos.</p></div><fieldset className="grid gap-3 sm:grid-cols-2"><label className="rounded-xl border p-4"><input type="radio" name="access" value="viewer" className="mr-2"/><strong>Visualizar</strong><span className="mt-1 block text-sm text-gray-500">A equipe pode consultar, mas não alterar.</span></label><label className="rounded-xl border border-emerald-300 bg-emerald-50 p-4"><input type="radio" name="access" value="support" defaultChecked className="mr-2"/><strong>Suporte</strong><span className="mt-1 block text-sm text-gray-600">Permite fazer os ajustes autorizados.</span></label></fieldset><button disabled={pending} className="w-full rounded-xl bg-[#063D2F] px-4 py-3 font-bold text-white disabled:opacity-60">{pending?"Gerando…":"Gerar código seguro"}</button>{state.error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{state.error}</p>}</form>
  <section className="rounded-2xl bg-[#063D2F] p-6 text-white shadow-xl"><ShieldCheck size={34} className="text-orange-400"/><h2 className="mt-4 text-xl font-bold">Código temporário</h2>{state.code?<><div className="mt-5 rounded-2xl bg-white p-5 text-center text-4xl font-black tracking-[.2em] text-[#063D2F]">{state.code}</div><button type="button" onClick={()=>navigator.clipboard.writeText(state.code!)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-white/20 px-4 py-3 font-bold"><Copy size={17}/>Copiar código</button><p className="mt-4 flex items-center gap-2 text-sm text-emerald-100"><Clock3 size={16}/>Válido até {new Date(state.expiresAt!).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</p></>:<p className="mt-4 text-sm text-emerald-100">O código aparecerá aqui. Passe apenas para um atendente oficial do MercadoFood.</p>}</section>
  </div>}
