import QRCode from "qrcode";
import { Armchair, Users, Clock3, ReceiptText } from "lucide-react";
import { requirePlanModule } from "@/lib/auth/current-company";
import { createTable, openTab, requestClosing, closeTab } from "./actions";

function money(v: number | string | null) { return new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL" }).format(Number(v || 0)); }
const colors: Record<string,string> = { available:"bg-emerald-50 text-emerald-800 border-emerald-200", occupied:"bg-orange-50 text-orange-800 border-orange-200", reserved:"bg-blue-50 text-blue-800 border-blue-200", disabled:"bg-gray-100 text-gray-600 border-gray-200" };
const labels: Record<string,string> = { available:"Livre", occupied:"Ocupada", reserved:"Reservada", disabled:"Desativada" };

export default async function MesasPage({ searchParams }: { searchParams: Promise<{ erro?:string; sucesso?:string }> }) {
  const query = await searchParams;
  const { supabase, company } = await requirePlanModule("tables");
  const { data: tables } = await supabase.from("restaurant_tables").select("id,name,code,seats,public_token,status,is_active, table_tabs(id,customer_name,customer_phone,guest_count,status,subtotal,service_charge,total,opened_at)").eq("company_id",company.id).eq("is_active",true).order("code");
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
  const prepared = await Promise.all((tables || []).map(async (table:any) => {
    const tab = (table.table_tabs || []).find((x:any) => ["open","requested_closing"].includes(x.status));
    const url = `${appUrl}/mesa/${table.public_token}`;
    return { ...table, tab, url, qr: await QRCode.toDataURL(url, { width:220, margin:1 }) };
  }));
  const occupied = prepared.filter(t => t.status === "occupied").length;
  const totalOpen = prepared.reduce((s,t) => s + Number(t.tab?.total || 0),0);
  return <main className="space-y-6">
    <header><p className="text-sm font-semibold text-emerald-700">Salão e atendimento presencial</p><h1 className="text-3xl font-bold">Mesas e comandas</h1><p className="text-gray-500">QR Code por mesa, pedidos adicionais e fechamento da conta.</p></header>
    {query.erro && <div className="rounded-xl bg-red-50 p-4 text-red-700">{query.erro}</div>}{query.sucesso && <div className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{query.sucesso}</div>}
    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><Armchair className="text-emerald-700"/><p className="mt-3 text-sm text-gray-500">Mesas ativas</p><strong className="text-3xl">{prepared.length}</strong></div><div className="rounded-2xl border bg-white p-5"><Users className="text-orange-600"/><p className="mt-3 text-sm text-gray-500">Ocupadas</p><strong className="text-3xl">{occupied}</strong></div><div className="rounded-2xl border bg-white p-5"><ReceiptText className="text-blue-600"/><p className="mt-3 text-sm text-gray-500">Total em aberto</p><strong className="text-3xl">{money(totalOpen)}</strong></div></section>
    <section className="grid gap-5 xl:grid-cols-[330px_1fr]">
      <form action={createTable} className="h-fit rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Cadastrar mesa</h2><label className="mt-4 block text-sm font-semibold">Nome</label><input name="name" required placeholder="Mesa 01" className="mt-1 w-full rounded-xl border px-3 py-3"/><label className="mt-3 block text-sm font-semibold">Código</label><input name="code" required placeholder="M01" className="mt-1 w-full rounded-xl border px-3 py-3 uppercase"/><label className="mt-3 block text-sm font-semibold">Lugares</label><input name="seats" type="number" min="1" defaultValue="4" className="mt-1 w-full rounded-xl border px-3 py-3"/><button className="mt-4 w-full rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white">Cadastrar mesa</button></form>
      <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{prepared.map((table:any) => <article key={table.id} className={`rounded-2xl border p-5 shadow-sm ${colors[table.status] || "bg-white"}`}><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide">{table.code}</p><h2 className="text-2xl font-bold">{table.name}</h2><p className="text-sm">{table.seats} lugares • {labels[table.status]}</p></div><img src={table.qr} alt={`QR Code ${table.name}`} className="h-24 w-24 rounded-lg bg-white p-1"/></div><p className="mt-2 break-all text-xs opacity-70">{table.url}</p>{!table.tab ? <form action={openTab} className="mt-4 space-y-2"><input type="hidden" name="tableId" value={table.id}/><input name="customerName" placeholder="Nome do cliente" className="w-full rounded-xl border bg-white px-3 py-2 text-gray-900"/><input name="customerPhone" placeholder="WhatsApp" className="w-full rounded-xl border bg-white px-3 py-2 text-gray-900"/><input name="guestCount" type="number" min="1" defaultValue="1" className="w-full rounded-xl border bg-white px-3 py-2 text-gray-900"/><button className="w-full rounded-xl bg-emerald-700 px-4 py-2 font-semibold text-white">Abrir comanda</button></form> : <div className="mt-4 rounded-xl bg-white/80 p-4 text-gray-900"><div className="flex items-center gap-2 text-sm text-gray-500"><Clock3 size={15}/> Comanda aberta</div><p className="mt-1 font-bold">{table.tab.customer_name || "Cliente da mesa"}</p><p className="text-sm">{table.tab.guest_count} pessoa(s)</p><div className="mt-3 flex justify-between"><span>Total</span><strong>{money(table.tab.total)}</strong></div>{table.tab.status === "requested_closing" && <p className="mt-2 rounded-lg bg-orange-100 p-2 text-sm font-semibold text-orange-800">Cliente solicitou a conta</p>}<div className="mt-3 grid gap-2"><form action={requestClosing}><input type="hidden" name="tabId" value={table.tab.id}/><button className="w-full rounded-xl border px-3 py-2 font-semibold">Solicitar fechamento</button></form><form action={closeTab} className="grid grid-cols-[1fr_auto] gap-2"><input type="hidden" name="tabId" value={table.tab.id}/><select name="paymentMethod" className="rounded-xl border px-2"><option value="cash">Dinheiro</option><option value="pix">PIX</option><option value="card_on_delivery">Cartão</option></select><button className="rounded-xl bg-gray-900 px-3 py-2 font-semibold text-white">Fechar</button></form></div></div>}</article>)}</div>
    </section>
  </main>;
}
