import Link from "next/link";
import { Bot, CheckCircle2, Megaphone, WalletCards } from "lucide-react";
import { requirePlanModule } from "@/lib/auth/current-company";
import { MediaManager } from "@/components/media/media-manager";
import type { MediaAsset } from "@/lib/media/types";
import { deleteCampaign, saveCampaign } from "./actions";
import { DeleteCampaignButton } from "./delete-button";

export const dynamic = "force-dynamic";
const money = (value: unknown) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value || 0));
const statusLabels: Record<string,string> = { draft:'Rascunho', awaiting_creative:'Aguardando criação', awaiting_payment:'Aguardando pagamento', ready:'Pronta para publicar', published:'Publicada', paused:'Pausada', rejected:'Rejeitada', canceled:'Cancelada' };

export default async function ImpulsionaPage({ searchParams }: { searchParams: Promise<{ campanha?: string; editar?: string; erro?: string; sucesso?: string }> }) {
  const query = await searchParams;
  const { supabase, company, role } = await requirePlanModule('marketing');
  const [{ data: campaigns }, { data: products }, { data: combos }, { data: promotions }] = await Promise.all([
    supabase.from('marketing_campaigns').select('*').eq('company_id', company.id).order('created_at',{ascending:false}),
    supabase.from('products').select('id,name').eq('company_id', company.id).eq('is_active',true).order('name'),
    supabase.from('combos').select('id,name').eq('company_id', company.id).eq('is_active',true).order('name'),
    supabase.from('promotions').select('id,name').eq('company_id', company.id).eq('is_active',true).order('name'),
  ]);
  const selectedId = query.campanha || query.editar;
  const selected = campaigns?.find(campaign => campaign.id === selectedId);
  const { data: media } = selected ? await supabase.from('media_assets').select('id,storage_path,public_url,alt_text,mime_type,byte_size,sort_order').eq('company_id',company.id).eq('entity_type','campaign').eq('entity_id',selected.id).order('sort_order') : { data: [] };
  const canManage = role === 'owner' || role === 'manager';

  return <main className="space-y-7 pb-16">
    <header className="rounded-3xl bg-gradient-to-r from-[#063D2F] to-emerald-700 p-6 text-white shadow-xl"><div className="flex items-center gap-3"><Megaphone className="text-orange-400" size={34}/><div><p className="text-sm font-semibold text-emerald-200">Novo módulo comercial</p><h1 className="text-3xl font-bold">MercadoFood Impulsiona</h1></div></div><p className="mt-3 max-w-3xl text-emerald-50">Monte uma campanha local com arte própria ou solicite a criação paga com IA. O valor da mídia, a taxa da plataforma e a criação aparecem separados antes de qualquer pagamento.</p></header>
    {query.erro && <p className="rounded-xl bg-red-50 p-4 text-red-700">{query.erro}</p>}{query.sucesso && <p className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{query.sucesso}</p>}
    {!canManage && <p className="rounded-xl bg-amber-50 p-4 text-amber-800">Somente proprietário ou gerente pode criar campanhas.</p>}
    {canManage && <section className="grid gap-5 xl:grid-cols-[1.6fr_1fr]">
      <form action={saveCampaign} className="space-y-5 rounded-3xl border bg-white p-6 shadow-sm"><input type="hidden" name="id" value={query.editar ? selected?.id || '' : ''}/><div><h2 className="text-xl font-bold">1. O que deseja divulgar?</h2><p className="text-sm text-gray-500">Escolha a oferta e o objetivo comercial.</p></div><label className="block text-sm font-semibold">Nome da campanha<input name="title" defaultValue={query.editar ? selected?.title : ''} required placeholder="Ex.: Combo da sexta-feira" className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"/></label><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">Tipo<select name="contentType" defaultValue={selected?.content_type || 'product'} className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"><option value="product">Produto</option><option value="combo">Combo</option><option value="promotion">Promoção</option><option value="menu">Cardápio completo</option><option value="custom">Campanha personalizada</option></select></label><label className="text-sm font-semibold">Item<select name="contentId" defaultValue={selected?.content_id || ''} className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"><option value="">Selecione, se necessário</option><optgroup label="Produtos">{products?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</optgroup><optgroup label="Combos">{combos?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</optgroup><optgroup label="Promoções">{promotions?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</optgroup></select></label></div><label className="block text-sm font-semibold">Objetivo<select name="objective" defaultValue={selected?.objective || 'orders'} className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"><option value="orders">Receber pedidos</option><option value="whatsapp">Conversas no WhatsApp</option><option value="menu">Visitas ao cardápio</option><option value="promotion">Divulgar promoção</option><option value="profile">Visitas ao perfil</option></select></label>
      <div><h2 className="text-xl font-bold">2. Como deseja criar?</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="rounded-2xl border-2 border-emerald-200 p-4"><input type="radio" name="creativeMode" value="own" defaultChecked={selected?.creative_mode !== 'ai'} className="mr-2"/><b>Já tenho minha arte</b><p className="mt-1 text-sm text-gray-500">Você envia a imagem após salvar.</p></label><label className="rounded-2xl border-2 border-violet-200 p-4"><input type="radio" name="creativeMode" value="ai" defaultChecked={selected?.creative_mode === 'ai'} className="mr-2"/><b className="text-violet-700">Criar com IA (+ R$ 19,90)</b><p className="mt-1 text-sm text-gray-500">Solicitação de arte e texto promocional.</p></label></div></div><label className="block text-sm font-semibold">Legenda<textarea name="caption" defaultValue={selected?.caption || ''} rows={3} placeholder="Descreva a oferta ou deixe instruções para a IA" className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"/></label><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">Botão<input name="cta" defaultValue={selected?.call_to_action || 'Pedir agora'} className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Link de destino<input name="destinationUrl" type="url" defaultValue={selected?.destination_url || ''} placeholder="https://..." className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"/></label></div>
      <div><h2 className="text-xl font-bold">3. Público e orçamento</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Raio (km)<input name="radiusKm" type="number" min="1" max="50" defaultValue={selected?.radius_km || 5} className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">R$ por dia<input name="dailyBudget" type="number" min="10" step="1" defaultValue={selected?.daily_budget || 20} className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Dias<input name="durationDays" type="number" min="1" max="30" defaultValue={selected?.duration_days || 5} className="mt-1 w-full rounded-xl border px-4 py-3 font-normal"/></label></div></div><button className="w-full rounded-xl bg-orange-500 py-3 font-bold text-white hover:bg-orange-600">{query.editar ? 'Salvar alterações' : 'Criar e revisar campanha'}</button></form>
      <aside className="space-y-4"><div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Como funciona</h2><div className="mt-4 space-y-4 text-sm"><p className="flex gap-2"><CheckCircle2 className="shrink-0 text-emerald-600" size={18}/>Você prepara a campanha e envia a arte.</p><p className="flex gap-2"><Bot className="shrink-0 text-violet-600" size={18}/>Se escolher IA, a criação é um serviço adicional pago.</p><p className="flex gap-2"><WalletCards className="shrink-0 text-orange-500" size={18}/>Nada é publicado ou cobrado sem revisão.</p></div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">A publicação automática na Meta será ativada após conectar conta de anúncios e gateway de pagamento. Nesta fase, a campanha fica pronta para revisão e suporte.</p></div></aside>
    </section>}
    {selected && <MediaManager companyId={company.id} entityType="campaign" entityId={selected.id} initialAssets={(media || []) as MediaAsset[]} title="Criativo da campanha" description="Envie a imagem principal. Para Feed, prefira o formato quadrado." recommendedSize="1080 × 1080 px (1:1)" maxFiles={4}/>} 
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Campanhas</h2><span className="text-sm text-gray-500">{campaigns?.length || 0} cadastradas</span></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{!campaigns?.length && <p className="rounded-xl bg-gray-50 p-6 text-gray-500">Nenhuma campanha criada.</p>}{campaigns?.map(campaign => <article key={campaign.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{campaign.title}</h3><p className="text-sm text-gray-500">{statusLabels[campaign.status] || campaign.status} · raio de {campaign.radius_km} km</p></div><b className="text-emerald-700">{money(campaign.total_due)}</b></div><div className="mt-3 grid grid-cols-3 gap-2 rounded-xl bg-gray-50 p-3 text-xs"><span>Mídia<br/><b>{money(campaign.media_budget)}</b></span><span>Taxa<br/><b>{money(campaign.platform_fee)}</b></span><span>IA<br/><b>{money(campaign.ai_fee)}</b></span></div><div className="mt-3 flex gap-2"><Link href={`/impulsiona?editar=${campaign.id}`} className="rounded-lg border px-3 py-2 text-sm font-semibold">Editar</Link><Link href={`/impulsiona?campanha=${campaign.id}`} className="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-800">Criativo</Link><form action={deleteCampaign}><input type="hidden" name="id" value={campaign.id}/><DeleteCampaignButton/></form></div></article>)}</div></section>
  </main>;
}
