"use server";
import { revalidatePath } from "next/cache";
import { requirePlatformStaff } from "@/lib/master/auth";

async function audit(admin:Awaited<ReturnType<typeof requirePlatformStaff>>["admin"],userId:string,companyId:string,action:string,oldValues:unknown,newValues:unknown){await admin.from("support_audit_logs").insert({staff_user_id:userId,company_id:companyId,action,old_values:oldValues,new_values:newValues,metadata:{source:"master_panel"}})}

export async function updateSubscription(formData:FormData){const {admin,user}=await requirePlatformStaff("master");const companyId=String(formData.get("companyId")||"");const planId=String(formData.get("planId")||"");const status=String(formData.get("status")||"");if(!companyId||!planId||!["trialing","active","past_due","suspended","canceled"].includes(status))return;const {data:before}=await admin.from("company_subscriptions").select("*").eq("company_id",companyId).single();const payload={plan_id:planId,status,updated_at:new Date().toISOString()};const {data:after}=await admin.from("company_subscriptions").update(payload).eq("company_id",companyId).select().single();await audit(admin,user.id,companyId,"master.subscription_updated",before,after);revalidatePath("/master");revalidatePath("/master/empresas")}

export async function addTrialDays(formData:FormData){const {admin,user}=await requirePlatformStaff("master");const companyId=String(formData.get("companyId")||"");const days=Math.max(1,Math.min(90,Number(formData.get("days")||3)));const {data:before}=await admin.from("company_subscriptions").select("*").eq("company_id",companyId).single();if(!before)return;const current=before.trial_ends_at?new Date(before.trial_ends_at).getTime():0;const base=Math.max(Date.now(),current);const trialEnds=new Date(base+days*86400000).toISOString();const {data:after}=await admin.from("company_subscriptions").update({status:"trialing",trial_ends_at:trialEnds,updated_at:new Date().toISOString()}).eq("company_id",companyId).select().single();await audit(admin,user.id,companyId,"master.trial_extended",before,after);revalidatePath("/master");revalidatePath("/master/empresas")}

export async function setModuleOverride(formData:FormData){const {admin,user}=await requirePlatformStaff("master");const companyId=String(formData.get("companyId")||"");const moduleKey=String(formData.get("moduleKey")||"");const enabled=String(formData.get("enabled"))==="true";if(!companyId||!moduleKey)return;const {data:before}=await admin.from("company_entitlement_overrides").select("*").eq("company_id",companyId).eq("module_key",moduleKey).maybeSingle();const {data:after}=await admin.from("company_entitlement_overrides").upsert({company_id:companyId,module_key:moduleKey,enabled,granted_by:user.id,reason:"Painel Master",updated_at:new Date().toISOString()},{onConflict:"company_id,module_key"}).select().single();await audit(admin,user.id,companyId,"master.module_override",before,after);revalidatePath("/master/empresas")}
